name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
    runs-on: [windows-latest, ubuntu-latest, macos-latest] #${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Windows MSVC, os: windows-latest, flags: -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl          }
          - { name: Windows Clang, os: windows-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
          - { name: Windows GCC, os: windows-latest, flags: -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ }
          # Too much for github runners, unecessary
          #- { name: Ubuntu Clang,  os: ubuntu-latest,  flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
          - { name: Ubuntu GCC,  os: ubuntu-latest,  flags: -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ }
          - { name: macOS Clang,   os: macos-latest,   flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        config:
          - { name: Debug, flags:   -DCMAKE_BUILD_TYPE=Debug }
          - { name: Release, flags: -DCMAKE_BUILD_TYPE=Release }

    steps:
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libxi-dev libudev-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -B build ${{matrix.platform.flags}} ${{matrix.config.flags}}

      - name: Build
        run: cmake --build build --config Release
