name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release, Debug]
        c_compiler: [clang]
        cpp_compiler: [clang++]

    steps:
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install libxrandr-dev libxcursor-dev libxi-dev libudev-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build ${{matrix.platform.flags}} ${{matrix.config.flags}}

      - name: Build
        run: cmake --build build --config Release
      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
